<a href="https://colab.research.google.com/github/JungYeoni/study_torch/blob/main/ML/Logistic%20Regression/nn_Module%EA%B3%BC_%ED%81%B4%EB%9E%98%EC%8A%A4%EB%A1%9C_%EA%B5%AC%ED%98%84%ED%95%98%EB%8A%94_%EB%A1%9C%EC%A7%80%EC%8A%A4%ED%8B%B1_%ED%9A%8C%EA%B7%80.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# nn.Module과 클래스로 구현하는 로지스틱 회귀

학습 자료
> https://wikidocs.net/58686

## 파이토치의 nn.Linear와 nn.Sigmoid로 로지스틱 회귀 구현하기

In [1]:
# 라이브러리 임포트
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [13]:
torch.manual_seed(1)

In [14]:
# 훈련 데이터 선언
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [15]:
# nn.Sequential
model = nn.Sequential(
    nn.Linear(2, 1),
    nn.Sigmoid() # 출력은 시그모이드 함수를 거친다
)

In [16]:
# 예측값 텐서 출력하기
model(x_train)

tensor([[0.4020],
        [0.4147],
        [0.6556],
        [0.5948],
        [0.6788],
        [0.8061]], grad_fn=<SigmoidBackward0>)

현재 파라미터는 임의의 값을 가지므로 현재의 예측은 의미 x

In [17]:
# optimizer 설정
optimizer = optim.SGD(model.parameters(), lr=1)

nb_epochs = 1000

for epoch in range(nb_epochs + 1):
  # H(x) 계산
  hypothesis = model(x_train)

  # cost 계산
  cost = F.binary_cross_entropy(hypothesis, y_train)

  # cost 로 H(x) 개선
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  # 20번 마다 로그 출력
  if epoch % 20 == 0:
    prediction = hypothesis >= torch.FloatTensor([0.5])
    correct_prediction = prediction.float() == y_train
    accuracy = correct_prediction.sum().item() / len(correct_prediction)
    print('Epoch {:4d}/{} Cost: {:.6f} Accuracy {:2.2f}%'.format(
        epoch, nb_epochs, cost.item(), accuracy * 100,
    ))

Epoch    0/1000 Cost: 0.539713 Accuracy 83.33%
Epoch   20/1000 Cost: 0.441875 Accuracy 66.67%
Epoch   40/1000 Cost: 0.316358 Accuracy 83.33%
Epoch   60/1000 Cost: 0.220498 Accuracy 100.00%
Epoch   80/1000 Cost: 0.157299 Accuracy 100.00%
Epoch  100/1000 Cost: 0.134272 Accuracy 100.00%
Epoch  120/1000 Cost: 0.118297 Accuracy 100.00%
Epoch  140/1000 Cost: 0.105779 Accuracy 100.00%
Epoch  160/1000 Cost: 0.095704 Accuracy 100.00%
Epoch  180/1000 Cost: 0.087420 Accuracy 100.00%
Epoch  200/1000 Cost: 0.080486 Accuracy 100.00%
Epoch  220/1000 Cost: 0.074595 Accuracy 100.00%
Epoch  240/1000 Cost: 0.069526 Accuracy 100.00%
Epoch  260/1000 Cost: 0.065118 Accuracy 100.00%
Epoch  280/1000 Cost: 0.061247 Accuracy 100.00%
Epoch  300/1000 Cost: 0.057820 Accuracy 100.00%
Epoch  320/1000 Cost: 0.054764 Accuracy 100.00%
Epoch  340/1000 Cost: 0.052022 Accuracy 100.00%
Epoch  360/1000 Cost: 0.049546 Accuracy 100.00%
Epoch  380/1000 Cost: 0.047299 Accuracy 100.00%
Epoch  400/1000 Cost: 0.045251 Accuracy 100

In [18]:
# 기존의 훈련 데이터 입력하여 예측값 확인
model(x_train)

tensor([[2.7616e-04],
        [3.1595e-02],
        [3.8959e-02],
        [9.5624e-01],
        [9.9823e-01],
        [9.9969e-01]], grad_fn=<SigmoidBackward0>)

In [19]:
# 훈련 후 파라미터 출력
print(list(model.parameters()))

[Parameter containing:
tensor([[3.2534, 1.5181]], requires_grad=True), Parameter containing:
tensor([-14.4839], requires_grad=True)]


## 인공 신경망으로 표현되는 로지스틱 회귀.

## 모델을 클래스로 구현하기

In [20]:
class BinaryClassifier(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(2, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, x): # model 객체를 데이터와 함께 호출하면 자동으로 실행됨
    return self.sigmoid(self.linear)

## 로지스틱 회귀 클래스로 구현하기

In [21]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [23]:
torch.manual_seed(1)

In [24]:
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [28]:
class BinaryClassifier(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(2, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, x): # model 객체를 데이터와 함께 호출하면 자동으로 실행됨
    return self.sigmoid(self.linear(x))

model = BinaryClassifier()

In [29]:
# optimizer 설정
optimizer = optim.SGD(model.parameters(), lr=1)

nb_epochs = 1000

for epochs in range(nb_epochs + 1):
  hypothesis = model(x_train)

  cost = F.binary_cross_entropy(hypothesis, y_train)

  # 개선
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 20 == 0:
    prediction = hypothesis >= torch.FloatTensor([0.5])
    correct_prediction = prediction.float() == y_train
    accuracy = correct_prediction.sum().item() / len(correct_prediction)

    print('Epoch {:4d}{} Cost: {:.6f} Accuracy: {:2.2f}%'.format(
        epoch, nb_epochs, cost.item(), accuracy * 100
    ))

Epoch 10001000 Cost: 0.778947 Accuracy: 33.33%
Epoch 10001000 Cost: 0.761915 Accuracy: 50.00%
Epoch 10001000 Cost: 1.365167 Accuracy: 50.00%
Epoch 10001000 Cost: 2.603027 Accuracy: 50.00%
Epoch 10001000 Cost: 0.632601 Accuracy: 66.67%
Epoch 10001000 Cost: 0.953450 Accuracy: 50.00%
Epoch 10001000 Cost: 1.970579 Accuracy: 50.00%
Epoch 10001000 Cost: 0.439057 Accuracy: 83.33%
Epoch 10001000 Cost: 0.454676 Accuracy: 66.67%
Epoch 10001000 Cost: 0.540655 Accuracy: 83.33%
Epoch 10001000 Cost: 0.606802 Accuracy: 66.67%
Epoch 10001000 Cost: 1.025490 Accuracy: 66.67%
Epoch 10001000 Cost: 0.515037 Accuracy: 50.00%
Epoch 10001000 Cost: 0.725775 Accuracy: 66.67%
Epoch 10001000 Cost: 0.523420 Accuracy: 50.00%
Epoch 10001000 Cost: 0.744208 Accuracy: 66.67%
Epoch 10001000 Cost: 0.483444 Accuracy: 66.67%
Epoch 10001000 Cost: 0.643554 Accuracy: 83.33%
Epoch 10001000 Cost: 0.464969 Accuracy: 66.67%
Epoch 10001000 Cost: 0.609912 Accuracy: 83.33%
Epoch 10001000 Cost: 0.446548 Accuracy: 66.67%
Epoch 1000100