<a href="https://colab.research.google.com/github/JungYeoni/study_torch/blob/main/nn_Module%EA%B3%BC_%ED%81%B4%EB%9E%98%EC%8A%A4%EB%A1%9C_%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  nn.Module과 클래스로 구현하기

학습자료
> https://wikidocs.net/55409

- 파이토치에 이미 구현되어져 제공되고 있는 함수들을 불러와 선형 회귀 모델 구현

## 단순 선형 회귀 구현하기

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [3]:
torch.manual_seed(1)

In [5]:
# 데이터 선언
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

`nn.Linear(input_dim, output_dim)`: 입력 차원과 출력 차원을 인자로 받는다

In [6]:
# 모델 선언 및 초기화
model = nn.Linear(1, 1)

In [7]:
# model에는 가중치와 편향이 저장되어 있음
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [8]:
# optimizer 설정 - SGD를 사용
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [10]:
# 전체 훈련 데이터에 대해 경사하강법을 2000회 반복
nb_epochs = 2000

for epoch in range(nb_epochs + 1):
  # H(x) 계산
  prediction = model(x_train)

  # cost 계산
  cost = F.mse_loss(prediction, y_train) # 파이토치에서 제공하는 평균제곱오차 사용

  '''cost로 H(x) 계산하는 부분'''

  # gradient를 0으로 초기화
  optimizer.zero_grad()

  # 비용 함수를 미분하여 gradient 계산
  cost.backward()

  # 파라미터 업데이트
  optimizer.step()

  if epoch % 100 == 0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [11]:
#  임의의 값을 넣어 모델이 예측하는 값 확인
new_var = torch.FloatTensor([[4.0]])

# 입력한 값 4에 대해서 예측 값 y를 리턴받아 pred_y에 저장
pred_y = model(new_var)

print('훈련 후 입력이 4일 때의 예측값:', pred_y)

훈련 후 입력이 4일 때의 예측값: tensor([[7.9989]], grad_fn=<AddmmBackward0>)


In [12]:
# 학습 후의 파라미터 출력
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


- forward 연산: 가설을 통해 입력 $x$로부터 예측된 $y$를 얻는 것
- backward 연산: 학습 과정에서 비용 함수를 미분하여 기울기를 구하는 것

## 다중 선형 회귀 구현하기

In [13]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [14]:
torch.manual_seed(1)

In [16]:
# 데이터 선언 - 3개의 x로부터 하나의 y를 예측하는 문제
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [17]:
# 모델 선언 및 초기화
model = nn.Linear(3, 1)

In [18]:
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]


In [19]:
# optimizer 정의
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [20]:
# 전체 훈련 데이터에 대해 경사하강법을 2000회 반복
nb_epochs = 2000

for epoch in range(nb_epochs + 1):
  # H(x) 계산
  prediction = model(x_train)

  # cost 계산
  cost = F.mse_loss(prediction, y_train) # 파이토치에서 제공하는 평균제곱오차 사용

  '''cost로 H(x) 계산하는 부분'''

  # gradient를 0으로 초기화
  optimizer.zero_grad()

  # 비용 함수를 미분하여 gradient 계산
  cost.backward()

  # 파라미터 업데이트
  optimizer.step()

  if epoch % 100 == 0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/2000 Cost: 31667.597656
Epoch  100/2000 Cost: 0.225993
Epoch  200/2000 Cost: 0.223911
Epoch  300/2000 Cost: 0.221941
Epoch  400/2000 Cost: 0.220059
Epoch  500/2000 Cost: 0.218271
Epoch  600/2000 Cost: 0.216575
Epoch  700/2000 Cost: 0.214950
Epoch  800/2000 Cost: 0.213413
Epoch  900/2000 Cost: 0.211952
Epoch 1000/2000 Cost: 0.210560
Epoch 1100/2000 Cost: 0.209232
Epoch 1200/2000 Cost: 0.207967
Epoch 1300/2000 Cost: 0.206761
Epoch 1400/2000 Cost: 0.205619
Epoch 1500/2000 Cost: 0.204522
Epoch 1600/2000 Cost: 0.203484
Epoch 1700/2000 Cost: 0.202485
Epoch 1800/2000 Cost: 0.201542
Epoch 1900/2000 Cost: 0.200635
Epoch 2000/2000 Cost: 0.199769


In [21]:
# 임의의 입력을 통해 예측값 확인
new_var = torch.FloatTensor([[73, 80, 75]])
pred_y = model(new_var)
print('훈련 후 입력이 73, 80, 75 일 때의 예측값: ', pred_y)

훈련 후 입력이 73, 80, 75 일 때의 예측값:  tensor([[151.2305]], grad_fn=<AddmmBackward0>)


In [22]:
# 파라미터 확인
print(list(model.parameters()))

[Parameter containing:
tensor([[0.9778, 0.4539, 0.5768]], requires_grad=True), Parameter containing:
tensor([0.2802], requires_grad=True)]


## 모델을 클래스로 구현하기

### 단순선형회귀

In [33]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [34]:
torch.manual_seed(1)

In [35]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [36]:
class LinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__() # nn.Module 클래스의 속성들을 가지고 초기화됨
    self.linear = nn.Linear(1, 1) # 단순 선형회귀이므로

  def forward(self, x):
    return self.linear(x)

In [37]:
model = LinearRegressionModel()

In [38]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [39]:
# 전체 훈련 데이터에 대해 경사하강법을 2000회 반복
nb_epochs = 2000

for epoch in range(nb_epochs + 1):
  # H(x) 계산
  prediction = model(x_train)

  # cost 계산
  cost = F.mse_loss(prediction, y_train) # 파이토치에서 제공하는 평균제곱오차 사용

  '''cost로 H(x) 계산하는 부분'''

  # gradient를 0으로 초기화
  optimizer.zero_grad()

  # 비용 함수를 미분하여 gradient 계산
  cost.backward()

  # 파라미터 업데이트
  optimizer.step()

  if epoch % 100 == 0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


### 다중 선형 회귀

In [40]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [41]:
torch.manual_seed(1)

In [42]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [43]:
class MultivariateLinearRegression(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(3, 1)

  def forward(self, x):
    return self.linear(x)

In [44]:
model = MultivariateLinearRegression()

In [45]:
# 전체 훈련 데이터에 대해 경사하강법을 2000회 반복
nb_epochs = 2000

for epoch in range(nb_epochs + 1):
  # H(x) 계산
  prediction = model(x_train)

  # cost 계산
  cost = F.mse_loss(prediction, y_train) # 파이토치에서 제공하는 평균제곱오차 사용

  '''cost로 H(x) 계산하는 부분'''

  # gradient를 0으로 초기화
  optimizer.zero_grad()

  # 비용 함수를 미분하여 gradient 계산
  cost.backward()

  # 파라미터 업데이트
  optimizer.step()

  if epoch % 100 == 0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/2000 Cost: 31667.597656
Epoch  100/2000 Cost: 31667.597656
Epoch  200/2000 Cost: 31667.597656
Epoch  300/2000 Cost: 31667.597656
Epoch  400/2000 Cost: 31667.597656
Epoch  500/2000 Cost: 31667.597656
Epoch  600/2000 Cost: 31667.597656
Epoch  700/2000 Cost: 31667.597656
Epoch  800/2000 Cost: 31667.597656
Epoch  900/2000 Cost: 31667.597656
Epoch 1000/2000 Cost: 31667.597656
Epoch 1100/2000 Cost: 31667.597656
Epoch 1200/2000 Cost: 31667.597656
Epoch 1300/2000 Cost: 31667.597656
Epoch 1400/2000 Cost: 31667.597656
Epoch 1500/2000 Cost: 31667.597656
Epoch 1600/2000 Cost: 31667.597656
Epoch 1700/2000 Cost: 31667.597656
Epoch 1800/2000 Cost: 31667.597656
Epoch 1900/2000 Cost: 31667.597656
Epoch 2000/2000 Cost: 31667.597656
