<a href="https://colab.research.google.com/github/JungYeoni/study_torch/blob/main/%EC%84%A0%ED%98%95_%ED%9A%8C%EA%B7%80%EC%99%80_%EC%9E%90%EB%8F%99_%EB%AF%B8%EB%B6%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 선형 회귀와 자동 미분

학습자료
> https://wikidocs.net/53560

## 1. 데이터 이해하기

- 공부한 시간과 점수에 대한 상관관계

## 2. 가설 수립하기


선형 회귀에서의 가설은 학습 데이터와 가장 잘 맞는 하나의 직선을 찾는 것

$H(x) = Wx + b$

## 3. 비용 함수(Cost Function)에 대한 이해

비용 함수(cost function) = 손실 함수(loss function) = 오차 함수(error function) = 목적 함수(objective function)

## 4. 옵티마이저 - 경사 하강법(Gradient Descent)

- 비용 함수의 값을 최소로 하는 $W$와  $b$를 찾는 방법을 옵티마이저 알고리즘이라고 함. (= 최적화 알고리즘)
- 이를 통해 적절한 $W$와  $b$를 찾는 과정을 머신러닝에서는 학습이라고 함.

## 5. 파이토치로 선형 회귀 구현하기

In [5]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [6]:
torch.manual_seed(1)

`torch.manua_seed()` 를 하는 이유
- `torch.manua_seed()` 를 사용한 프로그램의 결과는 다른 컴퓨터에서 실행시켜도 동일한 결과를 얻을 수 있음.


### 변수 선언

In [13]:
x_train = torch.FloatTensor([[1], [2], [3]]) # 공부한 시간
y_train = torch.FloatTensor([[2], [4], [6]]) # 점수

In [14]:
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [15]:
print(ｙ_train)
print(ｙ_train.shape)

tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


### 가중치와 편향 초기화
- 이 상태에서는 어떤 값이 들어가도 가설은 0을 예측하게됨

In [16]:
# 가중치를 0으로 초기화하고, 학습을 통해 값이 변경되는 변수임을 명시함.
W = torch.zeros(1, requires_grad=True)
# 가중치 출력
print(W)

tensor([0.], requires_grad=True)


In [17]:
# 편향 초기화
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


### 가설 세우기

In [23]:
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


### 비용 함수 선언하기

In [24]:
# 평균제곱오차
# torch.mean으로 평균 구하기
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


### 경사 하강법 구현하기

In [25]:
optimizer = optim.SGD([W, b], lr=0.1)

In [26]:
# gradient를 0으로 초기화
optimizer.zero_grad()
# 비용 함수를 미분하여 gradient 계산
cost.backward()
# W와 b를 업데이트
optimizer.step()

### 전체 코드

In [28]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [5]])

# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 1999 # 원하는만큼 경사하강법 반복
for epoch in range(nb_epochs + 1):
  # H(x) 계산
  hypothesis = x_train * W + b

  # cost 계산
  cost = torch.mean((hypothesis - y_train) ** 2)

  # cost로 H(x) 개선
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  # 100번 마다 로그 출력
  if epoch % 100 == 0:
    print("Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}".format(
        epoch, nb_epochs, W.item(), b.item(), cost.item()
    ))


Epoch    0/1999 W: 0.167, b: 0.073 Cost: 15.000000
Epoch  100/1999 W: 1.502, b: 0.662 Cost: 0.055558
Epoch  200/1999 W: 1.502, b: 0.663 Cost: 0.055557
Epoch  300/1999 W: 1.501, b: 0.664 Cost: 0.055557
Epoch  400/1999 W: 1.501, b: 0.664 Cost: 0.055556
Epoch  500/1999 W: 1.501, b: 0.665 Cost: 0.055556
Epoch  600/1999 W: 1.501, b: 0.665 Cost: 0.055556
Epoch  700/1999 W: 1.500, b: 0.666 Cost: 0.055556
Epoch  800/1999 W: 1.500, b: 0.666 Cost: 0.055556
Epoch  900/1999 W: 1.500, b: 0.666 Cost: 0.055556
Epoch 1000/1999 W: 1.500, b: 0.666 Cost: 0.055556
Epoch 1100/1999 W: 1.500, b: 0.666 Cost: 0.055556
Epoch 1200/1999 W: 1.500, b: 0.666 Cost: 0.055556
Epoch 1300/1999 W: 1.500, b: 0.666 Cost: 0.055556
Epoch 1400/1999 W: 1.500, b: 0.666 Cost: 0.055556
Epoch 1500/1999 W: 1.500, b: 0.667 Cost: 0.055556
Epoch 1600/1999 W: 1.500, b: 0.667 Cost: 0.055556
Epoch 1700/1999 W: 1.500, b: 0.667 Cost: 0.055556
Epoch 1800/1999 W: 1.500, b: 0.667 Cost: 0.055556
Epoch 1900/1999 W: 1.500, b: 0.667 Cost: 0.055556

## `optimizer.zero_grad()`가 필요한 이유

파이토치는 미분을 통해 얻은 기울기를 이전에 게산된 기울기 값에 누적시키는 특징이 있음

In [29]:
w = torch.tensor(2.0, requires_grad=True)

nb_epochs = 20

for epoch in range(nb_epochs + 1):
  z = 2 * w
  z.backward()

  print('수식을 w로 미분한 값: {}'.format(w.grad))

수식을 w로 미분한 값: 2.0
수식을 w로 미분한 값: 4.0
수식을 w로 미분한 값: 6.0
수식을 w로 미분한 값: 8.0
수식을 w로 미분한 값: 10.0
수식을 w로 미분한 값: 12.0
수식을 w로 미분한 값: 14.0
수식을 w로 미분한 값: 16.0
수식을 w로 미분한 값: 18.0
수식을 w로 미분한 값: 20.0
수식을 w로 미분한 값: 22.0
수식을 w로 미분한 값: 24.0
수식을 w로 미분한 값: 26.0
수식을 w로 미분한 값: 28.0
수식을 w로 미분한 값: 30.0
수식을 w로 미분한 값: 32.0
수식을 w로 미분한 값: 34.0
수식을 w로 미분한 값: 36.0
수식을 w로 미분한 값: 38.0
수식을 w로 미분한 값: 40.0
수식을 w로 미분한 값: 42.0


- 위와 같이 계속해서 미분값인 2가 누적되는 것을 확인할 수 있음.
- 그렇기 때문에 미분값을 0으로 초기화시켜줘야함.

## 자동 미분(Autograd) 실습하기

`requires_grad=True` 를 하면 그래프로부터 자동으로 미분이 계산된다.

In [30]:
# 임의의 식 작성
w = torch.tensor(2.0, requires_grad=True)

y = w**2
z = 2*y + 5

In [31]:
z.backward() # 해당 수식의 w에 대한 기울기 계산

In [32]:
print('수식을 w로 미분한 값: {}'.format(w.grad))

수식을 w로 미분한 값: 8.0
